[package]
name = "custom_cache_service"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.49.0", features = ["full"] }
bytes = "1.11.0"

# NOTE: package name is redis-protocol, crate name is redis_protocol
redis-protocol = { version = "6.0.0", features = ["bytes"] }

hashbrown = "0.16.1"
ahash = "0.8.12"
slab = "0.4.12"

clap = { version = "4.5.56", features = ["derive"] }

tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
thiserror = "2.0.18"