[package]
name = "custom_cache_service"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.40.0", features = ["full"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
regex = "1.10.6"
log = "0.4"
env_logger = "0.10"
byteorder = "1.5.0"
